"""Backward compatibility — use engram.core.tracing instead."""

from engram.core.tracing import (
    AVG_ACTIVATION,
    DREAMER_CYCLE,
    EDGES_TOTAL,
    EMBED_LATENCY,
    NODES_TOTAL,
    OPENROUTER_ERRORS,
    RECALL_LATENCY,
    RECONSOLIDATION_FAILURES,
    WRITE_LATENCY,
    Span,
    TraceCollector,
    add_log_level,
    get_trace,
    inject_context,
    set_correlation_id,
    set_owner_id,
    set_trace,
)

__all__ = [
    "AVG_ACTIVATION",
    "DREAMER_CYCLE",
    "EDGES_TOTAL",
    "EMBED_LATENCY",
    "NODES_TOTAL",
    "OPENROUTER_ERRORS",
    "RECALL_LATENCY",
    "RECONSOLIDATION_FAILURES",
    "WRITE_LATENCY",
    "Span",
    "TraceCollector",
    "add_log_level",
    "get_trace",
    "inject_context",
    "set_correlation_id",
    "set_owner_id",
    "set_trace",
]
